[OT185-103]organization documentation added
alkemyTech/OT185-server pull request #102
Opened 2022-05-16 07:05 UTC by tapi09

## Summary

### Type of change
- [X ] New feature
- [ ] New Tests
- [ ] Bug fix
- [X ] Refactor

### Checklist

- [X ] Traceability between this change and Jira.
- [ ] ```mvn clean install``` was run and all tests completed successfully.
- [X ] There are no unused variables and/or imports in the modified classes.
- [ ] There are no imports in the modified classes with the wildcard character. Ex: ```com.somepackage.*```.
- [ ] Slf4j was used for the application log instead ```System.out```.
- [ ] Public methods are documented with ```javadoc```.

2022-05-17 11:03 UTC, manerajona requested changes

2022-05-17 11:03 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/OrganizationApi.java
> +            @ApiResponse(responseCode = "200", description = "Successfully retrieved Organization", content = {@Content(mediaType = "JSON Value",
Por favor usar mediaType standard: `mediaType = MediaType.APPLICATION_JSON_VALUE`

2022-05-17 11:03 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/OrganizationApi.java
> +                    examples = @ExampleObject(value = "Incorrect parameters in JSON Object"))),
No hay un Json de entrada como para que de este error.

2022-05-17 11:03 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/OrganizationApi.java
> +                            examples = @ExampleObject(value = ("Organization ID is not found.")),
Este no es un ejemplo de error, ya que este es texto plano y el error de tipo `ErrorDetails`.

2022-05-17 11:03 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/OrganizationApi.java
> +            @ApiResponse(responseCode = "204", description = "Partial update", content = @Content),
Por favor borrar `content = @Content`

2022-05-17 11:03 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/OrganizationApi.java
> +            @ApiResponse(responseCode = "204", description = "Completely update", content = @Content),
Por favor borrar `content = @Content`

2022-05-17 11:03 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/OrganizationApi.java
> +            @ApiResponse(responseCode = "500", description = "Internal error", content = @Content)
Este método solo debería ser llamado por un usuario ADMIN, osea que puede devolver 401 (Unauthorized) y 403 (Forbidden)

2022-05-17 11:35 UTC, manerajona requested changes

2022-05-17 11:35 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/OrganizationApi.java
> +            @ApiResponse(responseCode = "200", description = "Successfully retrieved Organization slide list", content = {@Content(mediaType = "JSON Value",
Acá debería ser un array: `content = {@Content(mediaType = MediaType.APPLICATION_JSON_VALUE, array = @ArraySchema(schema = @Schema(implementation = SlideResponse.class)))})`

2022-05-21 11:45 UTC, manerajona requested changes

2022-05-21 11:45 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/OrganizationApi.java
> +            @ApiResponse(responseCode = "404", description = "Not found",
No debería devolver 404 sino un 200 con una lista vacía.

2022-05-21 20:17 UTC, tapi09 commented on src/main/java/com/alkemy/ong/ports/input/rs/api/OrganizationApi.java
> +            @ApiResponse(responseCode = "404", description = "Not found",
El id que viene es el de la organización, en caso de ingresar ingresar un id que no exista devuelve 404.

2022-05-21 21:48 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/OrganizationApi.java
> +            @ApiResponse(responseCode = "404", description = "Not found",
Claro tenes razón!

2022-05-21 21:48 UTC, merged