Activity model and Repo
alkemyTech/OT185-server pull request #21
Opened 2022-04-19 21:40 UTC by joelrodriguez-rgb

## Summary
https://alkemy-labs.atlassian.net/browse/OT185-21
COMO desarrollador 
QUIERO agregar la entidad Activity
PARA representar en la implementación la estructura de datos

Criterios de aceptación: 
Nombre de tabla: activity. Campos:
name: VARCHAR NOT NULL
content: TEXT NOT NULL
image: VARCHAR NOT NULL
timestamps y softDelete

### Type of change
- [x] New feature
### Checklist

- [x] Traceability between this change and Jira.
- [x] ```mvn clean install``` was run and all tests completed successfully.
- [x] There are no unused variables and/or imports in the modified classes.
- [x]There are no imports in the modified classes with the wildcard character. Ex: ```com.somepackage.*```.
- [x] Slf4j was used for the application log instead ```System.out```.
- [x] Public methods are documented with ```javadoc```.

2022-04-19 22:52 UTC, manerajona requested changes

2022-04-19 22:52 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/model/Activity.java
> +@SQLDelete(sql = "UPDATE alkymer SET is_active=false WHERE alkymer_id=?")
Corregir la query: `UPDATE activity SET is_active=false WHERE activity_id =?`

2022-04-19 22:52 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/model/Activity.java
> +    Long id;
Por favor, hacer los atributos de clase privados.

2022-04-19 23:11 UTC, joelrodriguez-rgb commented on src/main/java/com/alkemy/ong/domain/model/Activity.java
> +@SQLDelete(sql = "UPDATE alkymer SET is_active=false WHERE alkymer_id=?")
Resulto.

2022-04-19 23:11 UTC, joelrodriguez-rgb commented on src/main/java/com/alkemy/ong/domain/model/Activity.java
> +    Long id;
Resuelto.

2022-04-20 08:52 UTC, manerajona approved these changes

2022-04-20 08:52 UTC, merged