[OT185-19] News model and repository added
alkemyTech/OT185-server pull request #24
Opened 2022-04-20 04:55 UTC by Sabrina-Incinga

## Summary

### Type of change
- [ ] New feature
- [ ] New Tests
- [ ] Bug fix
- [ ] Refactor

### Checklist

- [ ] Traceability between this change and Jira.
- [ ] ```mvn clean install``` was run and all tests completed successfully.
- [ ] There are no unused variables and/or imports in the modified classes.
- [ ] There are no imports in the modified classes with the wildcard character. Ex: ```com.somepackage.*```.
- [ ] Slf4j was used for the application log instead ```System.out```.
- [ ] Public methods are documented with ```javadoc```.

2022-04-20 04:57 UTC, Sabrina-Incinga commented
Tuve que enviar de nuevo la pull request porque cometí el error de eliminar la otra rama al no saber cómo cambiar el nombre.

2022-04-20 08:41 UTC, manerajona requested changes

2022-04-20 08:41 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/model/News.java
> +    @ManyToOne(cascade = CascadeType.MERGE)
Por favor hacer agregarle: `@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)`

2022-04-20 08:41 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/model/News.java
> +    @JoinColumn(name = "category_id", insertable = false, updatable = false)
Cambiar **insertable** por **nullable**: `nullable = false`

2022-04-20 08:41 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/model/News.java
> +    private Category category;
Agregarle `@ToString.Exclude`

2022-04-21 12:47 UTC, manerajona approved these changes

2022-04-21 12:47 UTC, merged