[OT185-17] Users model and repository creation
alkemyTech/OT185-server pull request #25
Opened 2022-04-20 14:13 UTC by Aizuk

## Summary

Creation of user entity, SQL script and its repository

### Type of change
- [x] New feature
- [ ] New Tests
- [ ] Bug fix
- [ ] Refactor

### Checklist

- [ ] Traceability between this change and Jira.
- [x] ```mvn clean install``` was run and all tests completed successfully.
- [ ] There are no unused variables and/or imports in the modified classes.
- [ ] There are no imports in the modified classes with the wildcard character. Ex: ```com.somepackage.*```.
- [ ] Slf4j was used for the application log instead ```System.out```.
- [ ] Public methods are documented with ```javadoc```.

2022-04-20 16:09 UTC, manerajona requested changes

2022-04-20 16:09 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/model/User.java
> +public class User implements Auditable {
Por favor agregarle en para que implemente además de Auditable, **UserDetails**.

2022-04-20 16:09 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/model/User.java
> +
Porfavor agregar: 

```java
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.GrantedAuthority;
```

2022-04-20 16:09 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/model/User.java
> +    @Column(name = "email", nullable = false, updatable = false)
Agregar a email `unique = true`

2022-04-20 16:09 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/model/User.java
> +
Por favor agregar:

```java
   @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        if (this.role != null) {
            return Collections.singleton(this.role);
        }
        return Collections.emptySet();
    }

    @Override
    public String getUsername() {
        return this.email;
    }

    @Override
    public boolean isAccountNonExpired() {
        return false;
    }

    @Override
    public boolean isAccountNonLocked() {
        return false;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return false;
    }

    @Override
    public boolean isEnabled() {
        return audit.getIsActive();
    }
```

2022-04-20 16:14 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/model/User.java
> +
Agregale a la clase Role que implemente **GrantedAuthority** y el código de abajo:

```java
    @Override
    public String getAuthority() {
        return this.name;
    }
```

2022-04-20 17:03 UTC, Aizuk commented on src/main/java/com/alkemy/ong/domain/model/User.java
> +
@Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        if (this.role != null) {
            return Collections.singleton(this.role);
        }
        return Collections.emptySet();
    }
Al implementarlo marca error en el primer return, y pide castearle el tipo de la funcion a lo que devuelve. ¿Esta bien que lo haga?

A role le importe el import org.springframework.security.core.GrantedAuthority, pero me figura como que no lo uso, en gris. Y esto figura que no existe, que no puede hacer override:
@Override
    public String getAuthority() {
        return this.name;
    }

2022-04-21 12:41 UTC, manerajona approved these changes

2022-04-21 12:41 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/model/User.java
> +
@Aizuk  falta implementar la GrantedAuthority en Role.
Así: `public class Role implements GrantedAuthority`

2022-04-21 12:41 UTC, merged