[OT185-31] added jwt logic
alkemyTech/OT185-server pull request #34
Opened 2022-04-24 02:14 UTC by ItamMati

## Summary
COMO usuario
QUIERO estar autenticado en la plataforma
PARA poder acceder a todos sus servicios.

Criterios de aceptación:

Cuando el usuario se autentica, el servidor deberá generar un JSON Web Token con los datos del usuario, y devolver el mismo en la respuesta.

Para validar que el usuario está autenticado, el servidor deberá desencriptar este token, obteniéndolo del encabezado Authorization de la petición recibida.

### Type of change
- [ ] New feature
- [ ] New Tests
- [ ] Bug fix
- [ ] Refactor

### Checklist

- [ ] Traceability between this change and Jira.
- [ ] ```mvn clean install``` was run and all tests completed successfully.
- [ ] There are no unused variables and/or imports in the modified classes.
- [ ] There are no imports in the modified classes with the wildcard character. Ex: ```com.somepackage.*```.
- [ ] Slf4j was used for the application log instead ```System.out```.
- [ ] Public methods are documented with ```javadoc```.

2022-04-25 06:52 UTC, ItamMati commented
Se comenta la clase "UserServiceImpl" ya que implementa userdetails, que es implementado en la carpeta security.
En el tarea OT185-36 se descomenta y se colocan la lógica de negocio aplicada al usuario.

2022-04-26 09:38 UTC, manerajona requested changes

2022-04-26 09:38 UTC, manerajona commented on src/main/java/com/alkemy/ong/common/security/filter/JwtRequestFilter.java
> +    private final UserDetailsCustomService userDetailsCustomService;
Por favor usar la interfaz de spring `UserDetailsService`:

`private final UserDetailsService userService;`

2022-04-26 09:38 UTC, manerajona commented on src/main/java/com/alkemy/ong/common/security/filter/JwtRequestFilter.java
> +        final String authorizationHeader = request.getHeader("Authorization");
No harcodear el header, usar las constantes: `HttpHeaders.AUTHORIZATION`

2022-04-26 09:38 UTC, manerajona commented on src/main/java/com/alkemy/ong/common/security/filter/JwtRequestFilter.java
> +                UsernamePasswordAuthenticationToken authReq
Agregar pasword, authorities:

```java
UsernamePasswordAuthenticationToken authReq =
                            new UsernamePasswordAuthenticationToken(userDetails, userDetails.getPassword(), userDetails.getAuthorities());
```

2022-04-26 09:38 UTC, manerajona commented on src/main/java/com/alkemy/ong/common/security/services/AuthenticationService.java
> +        return jwt;
Podemos hacer este return en una sola linea:

`return jwtUtil.generateToken(userDetails);`

2022-04-26 09:38 UTC, manerajona commented on src/main/java/com/alkemy/ong/common/security/services/UserDetailsCustomService.java
> +package com.alkemy.ong.common.security.services;
Esto no debería estar acá sino en `com.alkemy.ong.domain.usecase.impl;`.

2022-04-26 09:38 UTC, manerajona commented on src/main/java/com/alkemy/ong/common/security/services/UserDetailsCustomService.java
> +    public UserDetails loadUserByUsername(String email) throws UsernameNotFoundException {
Esta lógica ya estaba hecha en la clase UserServiceImpl, usar esa porfavor y borrar esta

2022-04-26 09:38 UTC, manerajona commented on src/main/java/com/alkemy/ong/common/security/utils/JwtUtil.java
> +    private static final String SECRET_KEY = "4LK3MY4LK3MY4LK3MY4LK3MY4LK3MY4LK3MY4LK3MY4LK3MY4LK3MY4LK3MY4LK3MY4LK3MY4LK3MY4LK3MY";
Esta constante no debería estar harcodeada, sino en `application.properties`.

2022-04-26 09:38 UTC, manerajona commented on src/main/java/com/alkemy/ong/common/security/utils/JwtUtil.java
> +@Service
Cambiar a `@Component`

2022-04-26 09:38 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/impl/UserServiceImpl.java
> +//@RequiredArgsConstructor
Descomentar esto porfavor.

2022-04-26 09:38 UTC, manerajona commented on src/main/java/com/alkemy/ong/common/security/services/AuthenticationService.java
> +    public String singIn(AuthenticationRequest authRequest) throws Exception {
En vez de recibir el objeto `AuthenticationRequest`, hacerlo más general y recibir `username` y `password`.

2022-04-26 09:38 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/response/mapper/AlkymerControllerMapper.java
> +package com.alkemy.ong.ports.input.rs.response.mapper;
Por favor mover esta carpeta de vuelta a `com.alkemy.ong.ports.input.rs.mapper`

2022-04-26 09:38 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/response/mapper/CommonMapper.java
> +package com.alkemy.ong.ports.input.rs.response.mapper;
Igual que arriba.

2022-04-26 09:38 UTC, manerajona commented on src/main/resources/application.properties
> +spring.jackson.default-property-inclusion=non_nulL
No modificar esta propiedad por favor.

2022-04-26 11:52 UTC, ItamMati commented on src/main/resources/application.properties
> +spring.jackson.default-property-inclusion=non_nulL
No he tocado está propiedad, es más, no encuentro una diferencia entre una y otra.
Me llama la atención que la marque como si la hubiese tocado.

2022-04-26 12:33 UTC, ItamMati commented on src/main/java/com/alkemy/ong/common/security/services/AuthenticationService.java
> +    public String singIn(AuthenticationRequest authRequest) throws Exception {
Pero en ese caso también se puede aplicar @Valid? Qué ocurre si el cliente ingresa un correo sin @ o una contraseña que no cumpla con las validaciones exigidas en el registro. Para qué ocupar la base de datos para un caso que se sabe que no va a ser exitoso porque los atributos no fueron verificados.

2022-04-26 12:44 UTC, ItamMati commented on src/main/java/com/alkemy/ong/common/security/services/UserDetailsCustomService.java
> +    public UserDetails loadUserByUsername(String email) throws UsernameNotFoundException {
Cambié el método  loadUserByUsername ya que según investigué está ligado directamente a la seguridad, más allá que haga una revisión(no uso) de la información del usuario. Se me quedó lo que marcaste de que en el dominio debía ir todo lo ligado directamente a la lógica del negocio y aunque sabemos que es imprescindible , la seguridad no hace en sí al dominio entiendo. Por ejemplo, si yo retiro la seguridad del proyecto, el loadUserByUsername se utiliza para otra cosa??? Por eso lo implemente en la carpeta seguridad y comenté la que existía, claro que en el otro PR ya está descomentado y se utiliza.

2022-04-26 14:55 UTC, manerajona requested changes

2022-04-26 14:55 UTC, manerajona commented on src/main/java/com/alkemy/ong/common/security/services/AuthenticationService.java
> +    public String singIn(AuthenticationRequest authRequest) throws Exception {
No estas haciendo valid en esta clase sino en Controller. El objeto `AuthenticationRequest` es propio de la capa de rest, pero se podría autenticar por otro medio. Por favor generalizar la implementación.

2022-04-26 14:55 UTC, manerajona commented on src/main/resources/application.properties
> +spring.jackson.default-property-inclusion=non_nulL
Tiene una **L** al final que debería ser **l**.

2022-04-29 09:44 UTC, manerajona commented
@ItamMati alguna novedad con esto?

2022-04-29 13:15 UTC, manerajona requested changes

2022-04-29 13:15 UTC, manerajona commented on nb-configuration.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Agregar esto al .gitignore y no subirlo porfavor.

2022-04-29 13:15 UTC, manerajona commented on src/main/java/com/alkemy/ong/common/security/services/AuthenticationService.java
> +            throw new Exception("Incorrect username or password", e.getCause());
No capturar la excepción `BadCredentialsException` que ya la maneja spring. No tirar una Exception.

2022-04-29 13:15 UTC, manerajona commented on src/main/java/com/alkemy/ong/common/security/services/AuthenticationService.java
> +    public String singIn(String email, String password) throws Exception {
No devolver Exception en el método.

2022-04-29 13:15 UTC, manerajona commented on src/main/java/com/alkemy/ong/common/security/utils/JwtUtil.java
> +        System.out.println("Entro aca");
No usar System.out para logear.

2022-04-29 13:15 UTC, manerajona commented on src/main/java/com/alkemy/ong/common/security/services/AuthenticationService.java
> +            throw new Exception("Incorrect username or password", e.getCause());
Te debería quedar así

```java
Authentication auth = authenticationManager.authenticate(new UsernamePasswordAuthenticationToken(email, password));
UserDetails userDetails = (UserDetails) auth.getPrincipal();
return  jwtUtil.generateToken(userDetails);
```

2022-04-29 13:15 UTC, manerajona commented on src/main/resources/application.properties
> +<<<<<<< HEAD
Corregir este conflicto

2022-04-29 13:15 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/UserService.java
> +   UserResponse meData(String email);
Este método no corresponde con lo que pide la issue.

2022-04-29 13:15 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/UserService.java
> +   void deleteUserById(Long id);
igual que arriba.

2022-04-29 13:15 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/impl/UserServiceImpl.java
> +    public void deleteUserById(Long id) {findUserById(id).ifPresent(userJpaRepository::delete);}
Igual que arriba.

2022-04-29 13:15 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/impl/UserServiceImpl.java
> +        public UserResponse meData(String email) {
Igual que arriba.

2022-04-29 13:15 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/impl/UserServiceImpl.java
> +    private static Set<? extends GrantedAuthority> getAuthorities(User user) {
Este método no se usa nunca.

2022-04-29 13:15 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/impl/UserServiceImpl.java
> +        private Optional<User> findUserById(Long id) throws UsernameNotFoundException {
Este método no corresponde con lo que pide la issue.

2022-04-29 13:15 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/controller/AuthenticationController.java
> +    @GetMapping("/me")
Este endpoint no corresponde con lo que pide la issue.

2022-04-29 13:15 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/controller/UserController.java
> +public class UserController {
Esta clase no corresponde con lo que pide la issue.

2022-04-29 13:15 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/mapper/UserMapper.java
> +public interface UserMapper {
Esta clase no corresponde con lo que pide la issue.

2022-04-29 13:15 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/request/UpdateUserRequest.java
> +public class UpdateUserRequest {
Esta clase no corresponde con lo que pide la issue.

2022-04-29 13:15 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/response/UserResponse.java
> +public class UserResponse {
Esta clase no corresponde con lo que pide la issue.

2022-04-29 14:26 UTC, merged