Feature/ot185 27
alkemyTech/OT185-server pull request #38
Opened 2022-04-26 11:20 UTC by Daiana-Videla

## Summary
 OT185-27

### Type of change
- [x ] New feature
- [ ] New Tests
- [ ] Bug fix
- [ ] Refactor

### Checklist

- [ ] Traceability between this change and Jira.
- [ ] ```mvn clean install``` was run and all tests completed successfully.
- [ ] There are no unused variables and/or imports in the modified classes.
- [ ] There are no imports in the modified classes with the wildcard character. Ex: ```com.somepackage.*```.
- [ ] Slf4j was used for the application log instead ```System.out```.
- [ ] Public methods are documented with ```javadoc```.

2022-04-26 15:12 UTC, manerajona requested changes

2022-04-26 15:12 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/output/email/SendGridEmailService.java
> +        import com.sendgrid.Method;
Por favor, indentar bien los imports.

2022-04-26 15:12 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/output/email/SendGridEmailService.java
> +            System.out.println(ex.getMessage());
Por favor no usar System.out, usar log: https://javabydeveloper.com/lombok-slf4j-examples/

2022-04-26 15:12 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/output/email/SendGridEmailService.java
> +            System.out.println(ex.getMessage());
Tirar un throw new RuntimeException("mensaje")

2022-04-26 15:12 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/output/email/SendGridEmailService.java
> +        System.out.println("Status Code: " + response.getStatusCode() + ", Body: " + response.getBody() + ", Headers: "
No usar System out usar log

2022-04-26 15:12 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/output/email/SendGridEmailService.java
> +        System.out.println("Status Code: " + response.getStatusCode() + ", Body: " + response.getBody() + ", Headers: "
Igual que abajo

2022-04-26 15:12 UTC, manerajona commented on src/main/resources/application.properties
> +email.from= somosfundacionmas@gmail.com
Hay un espacio de más entre `=` y `somos...`

2022-04-26 15:12 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/output/email/SendGridEmailService.java
> +    private SendGrid sendGridClient;
Hacer esta variable final

2022-04-26 15:12 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/output/email/SendGridEmailService.java
> +    @Autowired
La annotación @Autowired no es necesaria

2022-04-28 12:16 UTC, Daiana-Videla commented on src/main/java/com/alkemy/ong/ports/output/email/SendGridEmailService.java
> +        import com.sendgrid.Method;
realizado

2022-04-28 12:17 UTC, Daiana-Videla commented on src/main/java/com/alkemy/ong/ports/output/email/SendGridEmailService.java
> +            System.out.println(ex.getMessage());
modificado

2022-04-28 12:17 UTC, Daiana-Videla commented on src/main/java/com/alkemy/ong/ports/output/email/SendGridEmailService.java
> +        System.out.println("Status Code: " + response.getStatusCode() + ", Body: " + response.getBody() + ", Headers: "
modificado

2022-04-28 12:17 UTC, Daiana-Videla commented on src/main/java/com/alkemy/ong/ports/output/email/SendGridEmailService.java
> +    private SendGrid sendGridClient;
modificado

2022-04-28 12:17 UTC, Daiana-Videla commented on src/main/java/com/alkemy/ong/ports/output/email/SendGridEmailService.java
> +    @Autowired
modificado

2022-04-28 12:17 UTC, Daiana-Videla commented on src/main/resources/application.properties
> +email.from= somosfundacionmas@gmail.com
modificado

2022-04-28 12:18 UTC, Daiana-Videla commented on src/main/java/com/alkemy/ong/ports/output/email/SendGridEmailService.java
> +        System.out.println("Status Code: " + response.getStatusCode() + ", Body: " + response.getBody() + ", Headers: "
modificado

2022-04-28 13:03 UTC, manerajona requested changes

2022-04-28 13:03 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/output/email/SendGridEmailService.java
> +        }catch (RuntimeException ex ){
Acá es lo que te decía, tenes que tirarla a la exception para que spring lo maneje no meterla en un catch sino no se entera de que hubo un error. Así te debería quedar:

```java
try {
// logic
} catch (IOException ex) {
   log.error("Error sending email", ex);
  throw new RuntimeException("Error sending email due " + ex);
}
```

2022-04-28 13:08 UTC, manerajona requested changes

2022-04-28 13:08 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/output/email/SendGridEmailService.java
> +        mail.setReplyTo(new Email("abc@gmail.com"));
No harcodear un email cualquiera, sino usar el de la organización que está en properties: `email.from`

2022-04-28 13:25 UTC, manerajona requested changes

2022-04-28 13:25 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/output/email/EmailService.java
> +    void sendText(String from, String to, String subject, String body);
Aca podemos sacar el String from ya que siempre va a ser `somosfundacionmas@gmail.com`

2022-04-28 13:25 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/output/email/EmailService.java
> +    void sendHTML(String from, String to, String subject, String body);
Aca podemos sacar el String from ya que siempre va a ser `somosfundacionmas@gmail.com`

2022-04-28 23:57 UTC, Daiana-Videla commented on src/main/java/com/alkemy/ong/ports/output/email/SendGridEmailService.java
> +        }catch (RuntimeException ex ){
ok, no lo habia entendido. gracias

2022-04-28 23:58 UTC, Daiana-Videla commented on src/main/java/com/alkemy/ong/ports/output/email/SendGridEmailService.java
> +        mail.setReplyTo(new Email("abc@gmail.com"));
modificado

2022-04-29 00:03 UTC, Daiana-Videla commented on src/main/java/com/alkemy/ong/ports/output/email/EmailService.java
> +    void sendHTML(String from, String to, String subject, String body);
modificado de a interface y de la clase que implementa la interface

2022-04-29 09:22 UTC, manerajona requested changes

2022-04-29 09:22 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/output/email/SendGridEmailService.java
> +        mail.setReplyTo(new Email("somosfundacionmas@gmail.com"));
No HARCODEAR los valores.

2022-04-29 09:22 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/output/email/SendGridEmailService.java
> +
Traer la variable usando `@Value("email.from")`

2022-04-29 09:22 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/output/email/EmailService.java
> +    void sendText(String from,  String subject, String body);
cambiar el nombre del parametro necesitado no sería `from`, sino `to`.

2022-04-29 09:22 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/output/email/EmailService.java
> +    void sendHTML(String from,  String subject, String body);
Igual que arriba.

2022-04-29 09:22 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/output/email/SendGridEmailService.java
> +        Mail mail = new Mail(new Email(from), subject, new Email(), content);
Acá le estas pasando el email `from`, y el email to vacío. Por favor pasar el email from que es siempre el mismo desde la variable en `email.from` y el email to es el que te pasan por parámetro. ¿Cómo está funcionando esto?

2022-05-02 20:16 UTC, manerajona approved these changes

2022-05-02 20:16 UTC, merged