[OT185-38] Testimonial creation Endpoint
alkemyTech/OT185-server pull request #44
Opened 2022-04-28 21:54 UTC by Aizuk

## Summary

COMO usuario administrador
QUIERO dar de alta nuevos Testimonios
PARA informar Novedades acerca de la ONG.

Criterios de aceptación:
POST /testimonials - Deberá validar la existencia de los campos name y content enviados, para almacenar el registro en la tabla testimonials.

postman screenshot added

### Type of change
- [x] New feature
- [ ] New Tests
- [ ] Bug fix
- [ ] Refactor

### Checklist

- [x] Traceability between this change and Jira.
- [x] ```mvn clean install``` was run and all tests completed successfully.
- [x] There are no unused variables and/or imports in the modified classes.
- [ ] There are no imports in the modified classes with the wildcard character. Ex: ```com.somepackage.*```.
- [ ] Slf4j was used for the application log instead ```System.out```.
- [ ] Public methods are documented with ```javadoc```.

![Testimony Post](https://user-images.githubusercontent.com/16806959/165852909-90c88e4f-59d9-41a0-a8ad-b09c8c7cd0ec.png)

2022-04-29 09:30 UTC, manerajona requested changes

2022-04-29 09:30 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/response/TestimonialResponse.java
> +public class TestimonialResponse {
Este response no es necesario, no lo subamos.

2022-04-29 09:30 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/mapper/TestimonialControllerMapper.java
> +    TestimonialResponse testimonialToTestimonialResponse (Testimonial testimonial);
Este mapeo no es necesario.

2022-04-29 09:30 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/controller/TestimonialController.java
> +    @ResponseStatus(HttpStatus.CREATED)
Estamos devolviendo CREATED pero sin el header Location. Necesitamos informarle al cliente que se creo.

2022-04-29 09:30 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/controller/TestimonialController.java
> +        testimonialService.createEntity(testimonial);
Devolver header location con la ubicación del recurso (URI). Como se muestra abajo:

```java
        URI location = ServletUriComponentsBuilder.fromCurrentRequest()
                .path("/{id}").buildAndExpand(id)
                .toUri();

        return ResponseEntity.created(location).build();
```

2022-04-29 09:30 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/TestimonialService.java
> +    void createEntity(Testimonial testimonial);
No devolver `void`, sino el `id` del recurso creado.

2022-05-01 17:07 UTC, manerajona requested changes

2022-05-01 17:07 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/request/CreateTestimonialRequest.java
> +    private Date startDate;
Este campo no corresponde a Testimonials.

2022-05-05 17:19 UTC, Aizuk commented on src/main/java/com/alkemy/ong/ports/input/rs/request/CreateTestimonialRequest.java
> +    private Date startDate;
deleteado

2022-05-05 20:18 UTC, closed without merging