[OT185-34] Update User
alkemyTech/OT185-server pull request #48
Opened 2022-04-29 06:20 UTC by ItamMati

## Summary
PATCH a /users/:id. En el caso de que el usuario no exista, devolverá un error 404.

### Type of change
- [ ] New feature
- [ ] New Tests
- [ ] Bug fix
- [ ] Refactor

### Checklist

- [ ] Traceability between this change and Jira.
- [ ] ```mvn clean install``` was run and all tests completed successfully.
- [ ] There are no unused variables and/or imports in the modified classes.
- [ ] There are no imports in the modified classes with the wildcard character. Ex: ```com.somepackage.*```.
- [ ] Slf4j was used for the application log instead ```System.out```.
- [ ] Public methods are documented with ```javadoc```.

2022-04-29 09:43 UTC, manerajona commented
@ItamMati hay cambios que no corresponden a la tarea. Por favor crear un nuevo branch a partir de main SIEMPRE, no de otros branches.

2022-04-29 09:44 UTC, manerajona requested changes

2022-04-29 09:44 UTC, manerajona commented on nb-configuration.xml
> +    <properties xmlns="http://www.netbeans.org/ns/maven-properties-data/1">
No subir cambios que no corresponden a la tarea asignada. Lo mismo para los otros cambios que no corresponden.

2022-04-29 21:38 UTC, manerajona requested changes

2022-04-29 21:38 UTC, manerajona commented on src/main/resources/application.properties
> +<<<<<<< Updated upstream
Por favor no subir estos conflictos, ¿como está funcionando la aplicación?

2022-04-29 21:38 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/mapper/AuthenticationControllerMapper.java
> -     UserResponse toDto(User user);
Por favor no subir cambios que no sean relacionados a la tarea.

2022-04-29 21:38 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/controller/AuthenticationController.java
> -    private final UserService userService;
Por favor no subir cambios que no sean relacionados a la tarea.

2022-04-29 21:38 UTC, manerajona commented on src/main/java/com/alkemy/ong/common/security/services/AuthenticationService.java
> -
Por favor no subir cambios que no sean relacionados a la tarea.

2022-05-01 03:22 UTC, ItamMati commented on src/main/java/com/alkemy/ong/common/security/services/AuthenticationService.java
> -
Jonathan, entiendo que acá lo que he hecho es ordenar las importaciones y borrar las que no corresponden.
De ser así y estar entiendo bien. En que rama debería hacer correcciones de ese tipo?
Debería volver a la rama en dónde trabajé con JwtUtil y realizar el cambio ahí?

2022-05-01 03:29 UTC, ItamMati commented on src/main/java/com/alkemy/ong/ports/input/rs/mapper/AuthenticationControllerMapper.java
> -     UserResponse toDto(User user);
En este caso, cambié el nombre del método porque en un PR anterior me marcaste que me apegara a la nomenclatura que nos has dado como base. Entonces observé que en este caso tampoco la respeté  con respecto al mapper de Alkymer.  Entiendo que como me has puesto en el comentario que no hace al ticket que estoy subiendo, entonces la pregunta nuevamente en qué momento debo hacer ese tipo de correcciones?
O sí ya están aceptado y son parte del main, me olvido y lo dejo así?

2022-05-01 17:16 UTC, manerajona requested changes

2022-05-01 17:16 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/request/UpdateUserRequest.java
> +    private Long id;
El campo id no se debería poder actualizar.

2022-05-01 17:16 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/request/UpdateUserRequest.java
> +    private String email;
El campo email no se debería poder actualizar.

2022-05-01 17:16 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/mapper/UserControllerMapper.java
> +    User userRequestToUpdateUserRequest(UpdateUserRequest userRequest);
El nombre del método quedaría más descriptivo si fuera `updateUserRequestToUser`

2022-05-01 17:16 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/impl/UserServiceImpl.java
> +                    Optional.ofNullable(user.getPassword()).ifPresent(userJpa::setPassword);
Por favor encriptar password antes de guardarlo Acá la solución del error por dep. circular: https://github.com/alkemyTech/OT185-server/pull/50

2022-05-01 18:02 UTC, ItamMati commented on src/main/java/com/alkemy/ong/domain/usecase/impl/UserServiceImpl.java
> +                    Optional.ofNullable(user.getPassword()).ifPresent(userJpa::setPassword);
Jonathan, pero cómo debería trabajar con un fix. Miré si estaba incorporado al main y no lo vi.
Y el cambio no hace directamente al ticket más allá que lo aplique, hace a un ticket anterior.
Si aplico la solución en este ticket no sería el mismo concepto de que es de otra tarea?
Cómo que primero debería trabajarse en la tarea que corresponde??
Consulto para entender porque nunca he trabajado con un fix.

2022-05-01 20:19 UTC, ItamMati commented on src/main/java/com/alkemy/ong/domain/usecase/impl/UserServiceImpl.java
> +                    Optional.ofNullable(user.getPassword()).ifPresent(userJpa::setPassword);
Jonathan, te consulto en base a lo que me ha venido sucediendo. Entonces en el caso de un fix , puedo modificar lo que traje del main (en donde se encuentra el fix) y luego subirlo junto con la tarea aunque no sea en si parte de esta??
En ese caso se aceptan modificaciones realizadas fuera de la tarea??
Te pregunto esto porque entendía que una vez solucionado el fix, este se integraba al main y de ahí yo realizo un nuevo pull para terminar con la tarea que hizo saltar el fix.

2022-05-02 08:17 UTC, manerajona requested changes

2022-05-02 08:17 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/impl/UserServiceImpl.java
> +                    Optional.ofNullable(user.getPassword()).ifPresent(userJpa::setPassword);
El fix no está en main, está en un branch que parte de este. Hacele merge al PR que abrí para que se integre en este branch.

2022-05-02 14:46 UTC, ItamMati commented on src/main/java/com/alkemy/ong/domain/usecase/impl/UserServiceImpl.java
> +                    }
Jonathan, le tuve que agregar el if porque el encode no me estaba aceptando null, activaba el transaccional y seguía corriendo pero sin hacer los cambios.

2022-05-02 14:57 UTC, manerajona requested changes

2022-05-02 14:57 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/impl/UserServiceImpl.java
> +                    }
Esta bien, para que quede un poco más claro podrás separar la encriptación del set. Hacer algo así:
```java
if(user.getPassword() != null){
  String encoded = passwordEncoder.encode(user.getPassword());
  userJpa.setPassword(encoded);
}
```

2022-05-02 14:58 UTC, manerajona commented
@ItamMati podrás solucionar los conflictos con main.

2022-05-02 15:58 UTC, merged