[OT185-16] Base Role model and repository creation
alkemyTech/OT185-server pull request #7
Opened 2022-04-18 13:44 UTC by Aizuk

## Summary

Roles Model and Repostory created

### Type of change
- [ ] New feature

### Checklist

- [ ] Traceability between this change and Jira.
- [ ] ```mvn clean install``` was run and all tests completed successfully.
- [ ] There are no unused variables and/or imports in the modified classes.
- [ ] There are no imports in the modified classes with the wildcard character. Ex: ```com.somepackage.*```.
- [ ] Slf4j was used for the application log instead ```System.out```.
- [ ] Public methods are documented with ```javadoc```.

2022-04-18 14:53 UTC, manerajona requested changes

2022-04-18 14:53 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/model/RoleEntity.java
> +    @Column(name="description")
Agregarle también `nullable = false, updatable = false`

2022-04-18 14:53 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/model/RoleEntity.java
> +@Table(name="roles")
Borrar la anotación `@Table`, vamos a usar `@Entity` de hibernate

2022-04-18 14:53 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/model/RoleEntity.java
> +@Setter
Agregarle `@NoArgsConstructor`

2022-04-18 14:53 UTC, manerajona commented on src/main/resources/db/migration/V1.16__table_roles.sql
> +create table alkymer
La tabla sería `role`

2022-04-18 14:53 UTC, manerajona commented on src/main/resources/db/migration/V1.16__table_roles.sql
> +drop table if exists roles;
La tabla va en singular, sería `role`

2022-04-18 14:53 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/model/RoleEntity.java
> +public class RoleEntity {
El nombre de la clase debería ser `Role`

2022-04-18 14:53 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/model/RoleEntity.java
> +@Entity
Agregar el nombre de la tabla: `@Entity(name="role")`

2022-04-18 18:31 UTC, Aizuk commented on src/main/java/com/alkemy/ong/domain/model/RoleEntity.java
> +public class RoleEntity {
Entiendo entonces que, ademas de lo de arriba, @Table(name="roles") debiera ser @Table(name="role")

2022-04-18 18:40 UTC, Aizuk commented
Ahi hice unas correcciones @manerajona

2022-04-18 19:14 UTC, manerajona requested changes

2022-04-18 19:14 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/model/Role.java
> +
Esto no lo especifica claramente pero cuando la US dice "timestamp" hace referencia a agregarle la columna `created_at`. (agregarla también al script).

```java
    @Column(name = "created_at", nullable = false, updatable = false)
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime createdAt;
```

2022-04-18 19:27 UTC, Aizuk commented on src/main/java/com/alkemy/ong/domain/model/Role.java
> +
Okis, agrego!

2022-04-18 19:36 UTC, Aizuk commented
Ahi va, corregi ademas una cosa que se me paso: En el repository quedo importada la clase vieja de RoleEntity y no creaba la tabla.

2022-04-19 08:49 UTC, manerajona approved these changes

2022-04-19 08:49 UTC, merged