[OT185- 46] Add new in the system
alkemyTech/OT185-server pull request #73
Opened 2022-05-05 13:15 UTC by ItamMati

## Summary
COMO usuario administrador
QUIERO agregar una novedad en el sistema
PARA poder informar las Novedades de la ONG

Criterios de aceptación:
POST /news - Deberá validar la existencia de los campos enviados, para almacenar el registro en la tabla News. Antes de almacenarla, deberá asignarle la columna Category con el valor "General News & Current Affairs"

### Type of change
- [ ] New feature
- [ ] New Tests
- [ ] Bug fix
- [ ] Refactor

### Checklist

- [ ] Traceability between this change and Jira.
- [ ] ```mvn clean install``` was run and all tests completed successfully.
- [ ] There are no unused variables and/or imports in the modified classes.
- [ ] There are no imports in the modified classes with the wildcard character. Ex: ```com.somepackage.*```.
- [ ] Slf4j was used for the application log instead ```System.out```.
- [ ] Public methods are documented with ```javadoc```.

2022-05-05 14:48 UTC, ItamMati commented on src/main/java/com/alkemy/ong/ports/input/rs/controller/NewsController.java
> +
Jonathan, me quedó picando esto:
Descripción
COMO usuario administrador
QUIERO agregar una novedad en el sistema
PARA poder informar las Novedades de la ONG
Criterios de aceptación:
POST /news - Deberá validar la existencia de los campos enviados, para almacenar el registro en la tabla News. Antes de almacenarla, deberá asignarle la columna Category con el valor "General News & Current Affairs".
Me dijiste que toda novedad tiene Categoría "General News & Current Affairs" , pero en que caso se usarían las otras categorías??
Ósea, quien crea una novedad  la categoriza, es decir, el post recibe un id categoría según el tema al que está relacionado la novedad.
O no?? O categoría también  tiene otra relación con alguna otra entidad?? (editado

2022-05-05 14:48 UTC, ItamMati commented on src/main/java/com/alkemy/ong/ports/input/rs/controller/NewsController.java
> +
Jonathan, me quedó picando esto:
Descripción
COMO usuario administrador
QUIERO agregar una novedad en el sistema
PARA poder informar las Novedades de la ONG
Criterios de aceptación:
POST /news - Deberá validar la existencia de los campos enviados, para almacenar el registro en la tabla News. Antes de almacenarla, deberá asignarle la columna Category con el valor "General News & Current Affairs".
Me dijiste que toda novedad tiene Categoría "General News & Current Affairs" , pero en que caso se usarían las otras categorías??
Ósea, quien crea una novedad  la categoriza, es decir, el post recibe un id categoría según el tema al que está relacionado la novedad.
O no?? O categoría también  tiene otra relación con alguna otra entidad?? (editado

2022-05-06 09:13 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/controller/NewsController.java
> +
Son lógicas las preguntas que haces, pero están fuera del scope de la tarea. Por el momento se almacenarían todas con la misma categoría.

2022-05-06 12:13 UTC, ItamMati commented on src/main/java/com/alkemy/ong/ports/input/rs/controller/NewsController.java
> +
Entendido.

2022-05-08 11:09 UTC, manerajona requested changes

2022-05-08 11:09 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/impl/NewsServiceImpl.java
> +                 .orElseThrow(() -> new UsernameNotFoundException("Category id: %s not found".formatted(newCategoryId)));
Podemos acá en vez de tirar una excepción, agregar la categoría "General News & Current Affairs" como dice la tarea.

2022-05-08 11:09 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/request/CreateNewsRequest.java
> +    @JsonProperty("categoryId")
Debe ser camel_case: `category_id`

2022-05-08 11:09 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/mapper/NewsControllerMapper.java
> +    News newsRequestToNews(CreateNewsRequest createNewsRequest);
Sería `createNewsRequestToNews`

2022-05-08 11:09 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/controller/NewsController.java
> +import com.alkemy.ong.ports.input.rs.request.CreateAlkymerRequest;
Sacar los imports que no se utilizan, por favor.

2022-05-08 11:09 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/mapper/NewsControllerMapper.java
> +import com.alkemy.ong.ports.input.rs.request.CreateUserRequest;
Sacar los imports que no se utilizan, por favor.

2022-05-10 09:21 UTC, manerajona requested changes

2022-05-10 09:21 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/mapper/NewsControllerMapper.java
> +import com.alkemy.ong.ports.input.rs.request.CreateUserRequest;
@ItamMati porfavor remover este import.

2022-05-10 09:21 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/impl/NewsServiceImpl.java
> +    private static Long newCategoryId = Long.valueOf(6);
Por favor colocar constantes en UPPER_SNAKE_CASE y colocarle un nombre más significativo, por ejemplo `GENERAL_NEW_ID` para saber que significa ese número. Ver: https://flaviocopes.com/magic-numbers/

2022-05-10 09:21 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/impl/NewsServiceImpl.java
> +    public Long createEntity(News news, Long CategoryId){
El parametro `CategoryId` nunca se utiliza. Por que no hacemos algo así:

```java
        Category category  = categoryJpaRepository.findById(CategoryId)
                .orElseGet(() -> categoryJpaRepository.findById(newCategoryId).get());

        news.setCategory(category);
```

2022-05-10 21:50 UTC, merged