[OT185-47] Update of news
alkemyTech/OT185-server pull request #74
Opened 2022-05-05 13:39 UTC by ItamMati

## Summary
COMO usuario administrador
QUIERO actualizar una novedad existente
PARA poder mantener a información actualizada

Criterios de aceptación:
PUT /news/:id - Deberá validar que la novedad exista en base al id enviado por parámetro. En el caso de que no exista devolver un error, caso contrario actualizar la novedad y devolver la misma con los datos actualizados

### Type of change
- [ ] New feature
- [ ] New Tests
- [ ] Bug fix
- [ ] Refactor

### Checklist

- [ ] Traceability between this change and Jira.
- [ ] ```mvn clean install``` was run and all tests completed successfully.
- [ ] There are no unused variables and/or imports in the modified classes.
- [ ] There are no imports in the modified classes with the wildcard character. Ex: ```com.somepackage.*```.
- [ ] Slf4j was used for the application log instead ```System.out```.
- [ ] Public methods are documented with ```javadoc```.

2022-05-06 09:07 UTC, manerajona requested changes

2022-05-06 09:07 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/impl/NewsServiceImpl.java
> +        news.setName(request.getName());
Al ser un método PATCH debemos poder actualizar parcialmente un recurso, es decir que pueden venir valores null y no debemos actualizarlos. Validar que `request.get... != null`

2022-05-06 09:07 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/NewsService.java
> +import org.springframework.http.ResponseEntity;
Remover este import por favor.

2022-05-08 11:16 UTC, manerajona requested changes

2022-05-08 11:16 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/impl/NewsServiceImpl.java
> +        Optional.ofNullable(request.getName()).ifPresent(news::setName);
Al ser un método PUT los valores deben ser remplazados por más que sean nulos.

2022-05-08 11:16 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/impl/NewsServiceImpl.java
> +        Optional.ofNullable(request.getContent()).ifPresent(news::setContent);
Igual que arriba

2022-05-08 11:16 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/impl/NewsServiceImpl.java
> +        Optional.of(request.getImage()).ifPresent(news::setImage);
Igual que arriba

2022-05-08 11:16 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/request/UpdateNewsRequest.java
> +}
Al ser PUT se actualiza la representación completa de News, faltaría `categoryId`.

2022-05-08 11:16 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/response/NewsResponse.java
> +
Faltaría `category`

2022-05-08 11:16 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/controller/NewsController.java
> +    @PatchMapping("/{id}")
La tarea pide que sea `PUT`

2022-05-08 11:16 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/controller/NewsController.java
> +import com.alkemy.ong.domain.model.User;
Borrar los imports que no se utilizan, por favor.

2022-05-08 23:43 UTC, ItamMati commented on src/main/java/com/alkemy/ong/domain/usecase/impl/NewsServiceImpl.java
> +        Optional.ofNullable(request.getName()).ifPresent(news::setName);
Hola Jonathan, más arriba entiendo que me pones lo contrario. El método con el que ingresa en el controller es un PATCH.
"Al ser un método PATCH debemos poder actualizar parcialmente un recurso, es decir que pueden venir valores null y no debemos actualizarlos. Validar que request.get... != null"

2022-05-09 00:06 UTC, ItamMati commented on src/main/java/com/alkemy/ong/domain/usecase/impl/NewsServiceImpl.java
> +        Optional.ofNullable(request.getName()).ifPresent(news::setName);
Hola Jonathan, es que más arriba pusiste lo contrario y lo corregí en base a eso. Ahora lo actualizo todo a put.

2022-05-09 08:31 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/impl/NewsServiceImpl.java
> +        Optional.ofNullable(request.getName()).ifPresent(news::setName);
¿Cómo lo contrario? Se remplaza la representación completa, no hay que validar si los valores son nulos.

2022-05-10 09:26 UTC, manerajona requested changes

2022-05-10 09:26 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/impl/NewsServiceImpl.java
> +        news.setCategory(request.getCategory());
¿Qué pasa si la category no existe? Deberíamos hacer la búsqueda y tirar un NotFoundException en caso de que no envíe una categoría.

2022-05-10 09:26 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/request/UpdateNewsRequest.java
> +
Agregar validaciones por favor, para los campos que sean nullable = false.

2022-05-10 21:55 UTC, manerajona commented
@ItamMati quedó con conflictos

2022-05-11 08:03 UTC, merged