[OT185-61] Contact list endpoint
alkemyTech/OT185-server pull request #78
Opened 2022-05-06 13:26 UTC by locknet11

## Summary
This PR adds: 
 - ContactController
 - ContactService
 - ContactServiceImpl
 
This PR modifies: 
 - Contact

### Type of change
- [x] New feature
- [ ] New Tests
- [ ] Bug fix
- [ ] Refactor

### Checklist

- [x] Traceability between this change and Jira.
- [x] ```mvn clean install``` was run and all tests completed successfully.
- [x] There are no unused variables and/or imports in the modified classes.
- [x] There are no imports in the modified classes with the wildcard character. Ex: ```com.somepackage.*```.
- [x] Slf4j was used for the application log instead ```System.out```.
- [x] Public methods are documented with ```javadoc```.

2022-05-08 11:27 UTC, manerajona requested changes

2022-05-08 11:27 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/controller/ContactController.java
> +	@PreAuthorize("hasRole('ROLE_ADMIN')")
¿El PreAuthorize está funcionando? Porque debería ser `hasRole('ADMIN')`

2022-05-08 12:13 UTC, manerajona requested changes

2022-05-08 12:13 UTC, manerajona commented on src/main/resources/db/migration/V1.61__add_contacts.sql
> +INSERT INTO contact (contact_id, name, phone, email, message, created_at, is_active) VALUES
Esto no lo subamos, por favor.

2022-05-09 12:07 UTC, locknet11 commented on src/main/java/com/alkemy/ong/ports/input/rs/controller/ContactController.java
> +	@PreAuthorize("hasRole('ROLE_ADMIN')")
Listo!

2022-05-09 12:07 UTC, locknet11 commented on src/main/resources/db/migration/V1.61__add_contacts.sql
> +INSERT INTO contact (contact_id, name, phone, email, message, created_at, is_active) VALUES
Listo, ya lo saque

2022-05-09 12:40 UTC, merged