[ OT185-86] Add documentation to NEWS
alkemyTech/OT185-server pull request #94
Opened 2022-05-13 13:50 UTC by ItamMati

## Summary
COMO desarrollador
QUIERO disponer de una documentación de los endpoints de Novedades
PARA tener referencias de su funcionamiento

Criterios de aceptación:
Se deberán documentar los diferentes endpoints especificando el modelo de datos, campos obligatorios, formato de la petición y ejemplo de la misma.

### Type of change
- [ ] New feature
- [ ] New Tests
- [ ] Bug fix
- [ ] Refactor

### Checklist

- [ ] Traceability between this change and Jira.
- [ ] ```mvn clean install``` was run and all tests completed successfully.
- [ ] There are no unused variables and/or imports in the modified classes.
- [ ] There are no imports in the modified classes with the wildcard character. Ex: ```com.somepackage.*```.
- [ ] Slf4j was used for the application log instead ```System.out```.
- [ ] Public methods are documented with ```javadoc```.

2022-05-17 10:47 UTC, manerajona requested changes

2022-05-17 10:47 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +                    content = { @Content(mediaType = "JSON Value")}),
Usar standard para mediatype `MediaType.APPLICATION_JSON_VALUE` y falta el contenido de la respuesta que sería `NewsResponse.class`

2022-05-17 10:47 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +                            examples = @ExampleObject(value="Incorrect parameters in JSON Object"))),
Para los errores se utiliza el objeto `ErrorDetails.class`

2022-05-17 10:47 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +                            examples = @ExampleObject(value="Incorrect parameters in JSON Object"))),
Para los errores se utiliza el objeto `ErrorDetails.class`

2022-05-17 10:47 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +                            examples = @ExampleObject(value = ("News's ID is not found."))
Igual que arriba, el en los errores no se utiliza String sino un objeto `ErrorDetails.class`

2022-05-17 10:47 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +                            examples = @ExampleObject(value = ("News's ID is not found."))
Igual que arriba, el en los errores no se utiliza String sino un objeto `ErrorDetails.class`

2022-05-17 10:47 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +                    ))
Este método solo puede ser modificado por usuarios ADMIN, osea que puede devolver 401 (Unauthorized) y 403 (Forbidden)

2022-05-17 10:47 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +                    ))
Este método solo puede ser modificado por usuarios ADMIN, osea que puede tirar 401 (Unauthorized) y 403 (Forbidden)

2022-05-17 10:47 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +                    content = { @Content(mediaType = "JSON Value")}),
Igual que arriba

2022-05-17 10:47 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +                    content = { @Content(mediaType = "JSON Value")}),
Igual que arriba

2022-05-17 10:47 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +                            examples = @ExampleObject(value="Incorrect parameter (ID)"))),
Igual que arriba

2022-05-17 10:47 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +                            examples = @ExampleObject(value="Incorrect parameter (ID)"))),
Igual que arriba

2022-05-17 10:47 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +                            examples = @ExampleObject(value = ("Id is not found."))
Igual que arriba

2022-05-17 10:47 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +                            examples = @ExampleObject(value = ("Id is not found."))
Igual que arriba

2022-05-17 10:47 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +                    ))
Este método puede ser acccedido por usuarios autenticados, osea que puede devolver 401 (Unauthorized).

2022-05-17 10:47 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +                    ))
Este método puede ser acccedido por usuarios autenticados, osea que puede devolver 401 (Unauthorized).

2022-05-17 10:47 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +                    content = { @Content(mediaType = "JSON Value")}),
Un 204 no devuelve contenido.

2022-05-17 10:47 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +                    content = { @Content(mediaType = "JSON Value")}),
Un 204 no devuelve contenido.

2022-05-17 10:47 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +                    content = { @Content(mediaType = "JSON Value")}),
En este caso 201 no devuelve contenido.

2022-05-17 10:47 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +                    content = { @Content(mediaType = "JSON Value")}),
En este caso 201 no devuelve contenido.

2022-05-17 10:47 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +                            examples = @ExampleObject(value="Incorrect parameter (ID)"))),
Falta 404 (no existe la news) y 401

2022-05-17 10:47 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +                            examples = @ExampleObject(value="Incorrect parameter (ID)"))),
Falta 404 y 401

2022-05-17 10:47 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +    )
Falta 401.

2022-05-17 10:47 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +    )
Falta 401 y 403.

2022-05-17 10:47 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +                    ))
Falta 401 y 403.

2022-05-17 10:47 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +                    ))
Falta 401 y 403.

2022-05-18 06:46 UTC, ItamMati commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +                            examples = @ExampleObject(value="Incorrect parameters in JSON Object"))),
Jonathan, agregué la clase que me decís pero deje el ejemplo ya que en la tarea lo pide. Quedo atento a si lo dejo o lo saco finalmente.

2022-05-21 11:39 UTC, manerajona requested changes

2022-05-21 11:39 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +                            schema = @Schema(implementation = ErrorDetails.class))}),
Acá devuelve `NewsResponse` no `ErrorDetails`

2022-05-21 11:39 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +                    content = { @Content(mediaType = MediaType.APPLICATION_JSON_VALUE)}),
Acá falta agregar el contenido que es `NewsResponse`

2022-05-21 11:39 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +                    content = { @Content(mediaType = MediaType.APPLICATION_JSON_VALUE)}),
Falta agregar el contenido que sería un array de `CommentResponse`. 

```java
content = {@Content(mediaType = MediaType.APPLICATION_JSON_VALUE,
                            array = @ArraySchema(schema = @Schema(implementation = CommentResponse.class)),
```

2022-05-21 11:39 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/NewsApi.java
> +    }
Podría devolver además un `403` Forbidden.

2022-05-22 15:26 UTC, merged